# Generated by Django 5.0.2 on 2024-02-16 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaltrainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaltrainer.sessiontype'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trainer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaltrainer.trainer'),
        ),
    ]
