# Generated by Django 5.0.2 on 2024-02-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaltrainer', '0002_sessiontype_trainer_alter_booking_session_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
