# Generated by Django 5.0.2 on 2024-02-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaltrainer', '0004_remove_booking_approved_remove_booking_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
